dtb-$(CONFIG_ARCH_MSM8996) += msm8996pro-pmi8996-mtp_15811_PVT3.dtb msm8996pro-v1.1-pmi8994-mtp_15811_PVT3.dtb
#	msm8996-v2-pmi8994-cdp.dtb \
	msm8996-v2-pmi8994-mtp.dtb \
	msm8996-v2-pmi8994-pmk8001-cdp.dtb \
	msm8996-v2-pmi8994-pmk8001-mtp.dtb \
	msm8996-v2-pmi8994-pm8004-cdp.dtb \
	msm8996-v2-pmi8994-pm8004-mtp.dtb \
	msm8996-v2-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996-v2-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996-v2-fluid.dtb \
	msm8996-v2-liquid.dtb \
	msm8996-v2-dtp.dtb \
	msm8996-v3-pmi8994-cdp.dtb \
	msm8996-v3-pmi8994-mtp.dtb \
	msm8996-v3-pmi8994-pmk8001-cdp.dtb \
	msm8996-v3-pmi8994-pmk8001-mtp.dtb \
	msm8996-v3-pmi8994-pm8004-cdp.dtb \
	msm8996-v3-pmi8994-pm8004-mtp.dtb \
	msm8996-v3-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996-v3-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996-v3-pmi8996-cdp.dtb \
	msm8996-v3-pmi8996-mtp.dtb \
	msm8996-v3-pmi8996-pmk8001-cdp.dtb \
	msm8996-v3-pmi8996-pmk8001-mtp.dtb \
	msm8996-v3-fluid.dtb \
	msm8996-v3-liquid.dtb \
	msm8996-v3-dtp.dtb \
	msm8996-v3-pm8004-mmxf-adp.dtb \
	msm8996-v3-pm8004-agave-adp.dtb \
	msm8996pro-pmi8994-cdp.dtb \
	msm8996pro-pmi8994-mtp.dtb \
	msm8996pro-pmi8994-pmk8001-cdp.dtb \
	msm8996pro-pmi8994-pmk8001-mtp.dtb \
	msm8996pro-pmi8994-pm8004-cdp.dtb \
	msm8996pro-pmi8994-pm8004-mtp.dtb \
	msm8996pro-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996pro-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996pro-pmi8996-cdp.dtb \
	msm8996pro-pmi8996-mtp.dtb \
	msm8996pro-pmi8996-pmk8001-cdp.dtb \
	msm8996pro-pmi8996-pmk8001-mtp.dtb \
	apq8096pro-liquid.dtb \
	msm8996-v3.0-pmi8994-cdp.dtb \
	msm8996-v3.0-pmi8994-mtp.dtb \
	msm8996-v3.0-pmi8994-pm8004-cdp.dtb \
	msm8996-v3.0-pmi8994-pm8004-mtp.dtb \
	msm8996-v3.0-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996-v3.0-pmi8994-pmk8001-cdp.dtb \
	msm8996-v3.0-pmi8996-cdp.dtb \
	msm8996-v3.0-pmi8996-mtp.dtb \
	msm8996-v3.0-fluid.dtb \
	msm8996-v3.0-liquid.dtb \
	msm8996-v3.0-dtp.dtb \
	apq8096-v2-pmi8994-cdp.dtb \
	apq8096-v2-pmi8994-mtp.dtb \
	apq8096-v2-pmi8994-pmk8001-cdp.dtb \
	apq8096-v2-pmi8994-pm8004-cdp.dtb \
	apq8096-v2-pmi8994-pm8004-pmk8001-cdp.dtb \
	apq8096-v2-liquid.dtb \
	apq8096-v2-dragonboard.dtb \
	apq8096-v2-auto-dragonboard.dtb \
	apq8096-v3-pmi8994-cdp.dtb \
	apq8096-v3-pmi8994-mtp.dtb \
	apq8096-v3-pmi8994-pmk8001-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-pmk8001-cdp.dtb \
	apq8096-v3-pmi8996-cdp.dtb \
	apq8096-v3-pmi8996-mtp.dtb \
	apq8096-v3-liquid.dtb \
	apq8096-v3-dragonboard.dtb \
	apq8096-v3-sbc.dtb \
	apq8096-v3-auto-dragonboard.dtb \
	apq8096-v3.0-pmi8994-cdp.dtb \
	apq8096-v3.0-pmi8994-mtp.dtb \
	apq8096-v3.0-pmi8994-pm8004-cdp.dtb \
	apq8096-v3.0-pmi8994-pm8004-pmk8001-cdp.dtb \
	apq8096-v3.0-pmi8994-pmk8001-cdp.dtb \
	apq8096-v3.0-pmi8996-cdp.dtb \
	apq8096-v3.0-pmi8996-mtp.dtb \
	apq8096-v3.0-liquid.dtb \
	apq8096-v3.0-dragonboard.dtb \
	apq8096-v3-pmi8994-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-pmk8001-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-pmk8001-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8996-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-mdm9x55-i2s-mtp.dtb \
	apq8096-v3-pmi8994-mdm9x55-slimbus-mtp.dtb \
	apq8096-v3-pmi8996-mdm9x55-i2s-mtp.dtb \
	apq8096-v3-pmi8996-mdm9x55-slimbus-mtp.dtb \
	apq8096-v3-pmi8996-dragonboard.dtb

dtb-$(CONFIG_SEC_HEROQLTE_PROJECT) += msm8996-sec-heroqlte-r00.dtb \
			 msm8996-sec-heroqlte-r01.dtb \
			 msm8996-sec-heroqlte-r02.dtb \
			 msm8996-sec-heroqlte-r03.dtb \
			 msm8996-sec-heroqlte-r05.dtb \
			 msm8996-sec-heroqlte-r06.dtb \
			 msm8996-sec-heroqlte-r07.dtb \
			 msm8996-sec-heroqlte-r08.dtb \
			 msm8996-sec-heroq-r09.dtb \
			 msm8996-sec-heroq-r09-v3.dtb \
			 msm8996-sec-heroqlte-r10.dtb \
			 msm8996-sec-heroqlte-r11.dtb \
			 msm8996-sec-heroqlte-r13.dtb \
			 msm8996-sec-heroqlte-r15.dtb

dtb-$(CONFIG_SEC_HERO2QLTE_PROJECT) += msm8996-sec-hero2qlte-r00.dtb \
			 msm8996-sec-hero2qlte-r01.dtb \
			 msm8996-sec-hero2qlte-r02.dtb \
			 msm8996-sec-hero2qlte-r03.dtb \
			 msm8996-sec-hero2qlte-r05.dtb \
			 msm8996-sec-hero2qlte-r06.dtb \
			 msm8996-sec-hero2qlte-r07.dtb \
			 msm8996-sec-hero2qlte-r08.dtb \
			 msm8996-sec-heroq-r09.dtb \
			 msm8996-sec-heroq-r09-v3.dtb \
			 msm8996-sec-hero2qlte-r10.dtb \
			 msm8996-sec-hero2qlte-r11.dtb \
			 msm8996-sec-hero2qlte-r13.dtb \
			 msm8996-sec-hero2qlte-r15.dtb \
			msm8996pro-pmi8994-cdp.dtb \
			msm8996pro-pmi8994-mtp.dtb \
			msm8996pro-pmi8994-pmk8001-cdp.dtb \
			msm8996pro-pmi8994-pmk8001-mtp.dtb \
			msm8996pro-pmi8994-pm8004-cdp.dtb \
			msm8996pro-pmi8994-pm8004-mtp.dtb \
			msm8996pro-pmi8994-pm8004-pmk8001-cdp.dtb \
			msm8996pro-pmi8994-pm8004-pmk8001-mtp.dtb \
			msm8996pro-pmi8996-cdp.dtb \
			msm8996pro-pmi8996-mtp.dtb \
			msm8996pro-pmi8996-pmk8001-cdp.dtb \
			msm8996pro-pmi8996-pmk8001-mtp.dtb \
			msm8996pro-pmi8996-mtp_15811_PVT3.dtb \
			msm8996pro-v1.1-pmi8994-mtp_15811_PVT3.dtb

dtb-$(CONFIG_SEC_AEROQLTE_PROJECT) += msm8996-sec-aeroqlte-r00.dtb \
			msm8996-sec-aeroqlte-r01.dtb \
			msm8996-sec-aeroqlte-r02.dtb \
			msm8996-sec-aeroqlte-r03.dtb

ifeq ($(filter y,$(CONFIG_MACH_HEROQLTE_DCM) $(CONFIG_MACH_HEROQLTE_KDI)),y)
dtb-y = msm8996-sec-heroqlte-jpn-r00.dtb \
			 msm8996-sec-heroqlte-jpn-r01.dtb \
			 msm8996-sec-heroqlte-jpn-r05.dtb \
			 msm8996-sec-heroqlte-jpn-r06.dtb \
			 msm8996-sec-heroqlte-jpn-r07.dtb \
			 msm8996-sec-heroqlte-jpn-r08.dtb \
			 msm8996-sec-heroqlte-jpn-r10.dtb \
			 msm8996-sec-heroqlte-jpn-r11.dtb \
			 msm8996-sec-heroqlte-jpn-r13.dtb \
			 msm8996-sec-heroqlte-jpn-r15.dtb
endif

ifeq ($(filter y,$(CONFIG_MACH_HERO2QLTE_DCM) $(CONFIG_MACH_HERO2QLTE_KDI)),y)
dtb-y = msm8996-sec-hero2qlte-jpn-r00.dtb \
			 msm8996-sec-hero2qlte-jpn-r01.dtb \
			 msm8996-sec-hero2qlte-jpn-r05.dtb \
			 msm8996-sec-hero2qlte-jpn-r06.dtb \
			 msm8996-sec-hero2qlte-jpn-r07.dtb \
			 msm8996-sec-hero2qlte-jpn-r08.dtb \
			 msm8996-sec-hero2qlte-jpn-r10.dtb \
			 msm8996-sec-hero2qlte-jpn-r11.dtb \
			 msm8996-sec-hero2qlte-jpn-r13.dtb \
			 msm8996-sec-hero2qlte-jpn-r15.dtb
endif

ifeq ($(filter y,$(CONFIG_MACH_HEROQLTE_CHNZC)),y)
dtb-y = msm8996-sec-heroqlte-r00.dtb \
			 msm8996-sec-heroqlte-r01.dtb \
			 msm8996-sec-heroqlte-r02.dtb \
			 msm8996-sec-heroqlte-r03.dtb \
			 msm8996-sec-heroqlte-chn-r05.dtb \
			 msm8996-sec-heroqlte-chn-r06.dtb \
			 msm8996-sec-heroqlte-chn-r07.dtb \
			 msm8996-sec-heroqlte-chn-r08.dtb \
			 msm8996-sec-heroq-r09.dtb \
			 msm8996-sec-heroq-r09-v3.dtb \
			 msm8996-sec-heroqlte-chn-r10.dtb \
			 msm8996-sec-heroqlte-chn-r11.dtb \
			 msm8996-sec-heroqlte-chn-r13.dtb \
			 msm8996-sec-heroqlte-chn-r15.dtb

endif

ifeq ($(filter y,$(CONFIG_MACH_HERO2QLTE_CHNZC)),y)
dtb-y = msm8996-sec-hero2qlte-r00.dtb \
			 msm8996-sec-hero2qlte-r01.dtb \
			 msm8996-sec-hero2qlte-r02.dtb \
			 msm8996-sec-hero2qlte-r03.dtb \
			 msm8996-sec-hero2qlte-chn-r05.dtb \
			 msm8996-sec-hero2qlte-chn-r06.dtb \
			 msm8996-sec-hero2qlte-chn-r07.dtb \
			 msm8996-sec-hero2qlte-chn-r08.dtb \
			 msm8996-sec-heroq-r09.dtb \
			 msm8996-sec-heroq-r09-v3.dtb \
			 msm8996-sec-hero2qlte-chn-r10.dtb \
			 msm8996-sec-hero2qlte-chn-r11.dtb \
			 msm8996-sec-hero2qlte-chn-r13.dtb \
			 msm8996-sec-hero2qlte-chn-r15.dtb
endif

ifeq ($(CONFIG_ARM64),y)
always          := $(dtb-y)
subdir-y        := $(dts-dirs)
else
targets += dtbs
targets += $(addprefix ../, $(dtb-y))

$(obj)/../%.dtb: $(src)/%.dts FORCE
        $(call if_changed_dep,dtc)

dtbs: $(addprefix $(obj)/,$(dtb-y))
endif
clean-files := *.dtb *.reverse.dts
